### ISSUE TITLE
Can't copy coordinates

### ISSUE THREAD

**Issue by perilstar** [Yogu/itemfinder#1]
Since most people will be using this tool to teleport to their death point, I think it would be a good idea to make the coordinates copyable. Latest version on Ubuntu.

**Comment by Yogu** [comment]
Thanks for your feature suggestion, @ekyl! I just released [v0.2.2](https://github.com/Yogu/itemfinder/releases/tag/v0.2.2) in which you can right-click the cells (e.g. the coordinate cell) to copy the contents to the clipboard.

**Comment by perilstar** [comment]
You sure get on these fast!
